# _config.yml

# prevent Jekyll from trying to parse the .md files from docs/
exclude:
  - docs/**/*.md

algolia:
  application_id: 'R6Y1H83FNX'
  index_name: 'albums'
  files_to_exclude: []
  nodes_to_index: 'article'
